"""FFmpeg audiogram pipeline.

Builds and executes an FFmpeg command that composites:
  - A static background image (looped for the audio duration)
  - An animated waveform overlay (generated by waveform.py using FFT + Pillow)
  - Episode title text overlay
  - Optional duration indicator
  - Optional watermark / logo overlay

Output: 1920x1080 H.264/AAC MP4 optimised for YouTube.
"""
from __future__ import annotations

import asyncio
import logging
import os
import shutil
from pathlib import Path

from app.config import settings
from app.ffmpeg.escape import escape_drawtext, format_duration
from app.models.template import Template

logger = logging.getLogger(__name__)

VIDEO_W = 1920
VIDEO_H = 1080
FPS = 25


def _clamp(val: object, lo: int, hi: int) -> "int | str":
    """Clamp a template numeric value to a safe range.

    If *val* is a plain integer (or a string that represents one), clamp it.
    If it looks like an FFmpeg expression (e.g. ``(w-text_w)/2``), pass it
    through unchanged so FFmpeg can evaluate it at runtime.
    """
    try:
        return max(lo, min(hi, int(val)))  # type: ignore[arg-type]
    except (ValueError, TypeError):
        return val  # type: ignore[return-value]


def _resolve_font(template: Template) -> str:
    """Return the font path to use, falling back to system default."""
    if template.title_font_path and Path(template.title_font_path).exists():
        return template.title_font_path
    system = settings.default_font_path
    if Path(system).exists():
        return system
    return ""


def build_filter_complex(
    template: Template,
    title: str,
    duration_secs: int | None,
    has_watermark: bool,
    waveform_input_idx: int = 2,
) -> str:
    """Return the -filter_complex string for the FFmpeg command.

    waveform_input_idx: the FFmpeg input index of the pre-rendered waveform overlay.
    """
    font = _resolve_font(template)
    font_clause = f"fontfile='{font}':" if font else ""
    safe_title = escape_drawtext(title)

    parts: list[str] = []

    # ── 1. Scale background to 1920x1080 ────────────────────────────────────
    parts.append(f"[0:v]scale={VIDEO_W}:{VIDEO_H},setsar=1[bg]")

    # ── 2. Overlay pre-rendered waveform on background ───────────────────────
    wx = _clamp(template.waveform_x, 0, 3840)
    wy = _clamp(template.waveform_y, 0, 2160)
    parts.append(f"[bg][{waveform_input_idx}:v]overlay=x={wx}:y={wy}[comp1]")
    current = "comp1"

    # ── 3. Episode title drawtext ────────────────────────────────────────────
    title_drawtext = (
        f"[{current}]drawtext="
        f"{font_clause}"
        f"text='{safe_title}':"
        f"fontcolor={template.title_color}:"
        f"fontsize={_clamp(template.title_font_size, 8, 500)}:"
        f"x={_clamp(template.title_x, 0, 3840)}:"
        f"y={_clamp(template.title_y, 0, 2160)}:"
        f"line_spacing=4"
        f"[comp2]"
    )
    parts.append(title_drawtext)
    current = "comp2"

    # ── 4. Duration overlay (top-left corner) ───────────────────────────────
    if template.show_duration and duration_secs:
        dur_text = escape_drawtext(format_duration(duration_secs))
        dur_font = _resolve_font(template)
        dur_font_clause = f"fontfile='{dur_font}':" if dur_font else ""
        dur_drawtext = (
            f"[{current}]drawtext="
            f"{dur_font_clause}"
            f"text='{dur_text}':"
            f"fontcolor=#CCCCCC:"
            f"fontsize=36:"
            f"x=40:y=40"
            f"[comp3]"
        )
        parts.append(dur_drawtext)
        current = "comp3"

    # ── 5. Watermark overlay ─────────────────────────────────────────────────
    if has_watermark and template.watermark_path:
        wm_idx = waveform_input_idx + 1
        wm_scale = _clamp(template.watermark_scale, 10, 1920)
        parts.append(
            f"[{current}]null[pre_wm];"
            f"[{wm_idx}:v]scale={wm_scale}:-1[wm_scaled];"
            f"[pre_wm][wm_scaled]overlay="
            f"x={_clamp(template.watermark_x, 0, 3840)}:"
            f"y={_clamp(template.watermark_y, 0, 2160)}"
            f"[out]"
        )
    else:
        parts.append(f"[{current}]null[out]")

    return ";".join(parts)


def build_ffmpeg_cmd(
    background_path: str | None,
    mp3_path: str,
    waveform_path: str,
    output_path: str,
    template: Template,
    title: str,
    duration_secs: int | None,
) -> list[str]:
    """Return the full FFmpeg argument list."""
    has_watermark = bool(template.watermark_path and Path(str(template.watermark_path)).exists())

    if background_path and Path(background_path).exists():
        bg = background_path
    else:
        bg = str(Path(__file__).parent.parent / "static" / "img" / "default_bg.png")

    # Input layout:
    #   0 = background image (looped)
    #   1 = audio (MP3)
    #   2 = waveform overlay (pre-rendered MKV with alpha)
    #   3 = watermark (optional)
    waveform_input_idx = 2
    filter_complex = build_filter_complex(
        template, title, duration_secs, has_watermark, waveform_input_idx
    )

    cmd = [
        "ffmpeg", "-y",
        "-loop", "1", "-i", bg,
        "-i", mp3_path,
        "-i", waveform_path,
    ]

    if has_watermark:
        cmd += ["-i", str(template.watermark_path)]

    cmd += [
        "-filter_complex", filter_complex,
        "-map", "[out]",
        "-map", "1:a",
        "-c:v", "libx264",
        "-preset", "fast",
        "-crf", "23",
        "-c:a", "aac",
        "-b:a", "192k",
        "-pix_fmt", "yuv420p",
        "-shortest",
        "-movflags", "+faststart",
        output_path,
    ]

    return cmd


async def run_pipeline(
    mp3_path: str,
    output_path: str,
    template: Template,
    title: str,
    duration_secs: int | None,
) -> tuple[list[str], str]:
    """Execute the FFmpeg pipeline. Returns (cmd, stderr_log).

    Raises RuntimeError on non-zero FFmpeg exit code.
    """
    if not shutil.which("ffmpeg"):
        raise RuntimeError("ffmpeg not found in PATH. Install it with: apt-get install ffmpeg")

    from app.ffmpeg.waveform import generate_waveform_overlay

    ww = int(_clamp(template.waveform_w, 1, 3840))
    wh = int(_clamp(template.waveform_h, 1, 2160))

    logger.info("Generating waveform overlay (%dx%d)…", ww, wh)
    waveform_path = await generate_waveform_overlay(
        mp3_path=mp3_path,
        width=ww,
        height=wh,
        fps=FPS,
        color_hex=template.waveform_color,
    )
    logger.info("Waveform overlay ready: %s", waveform_path)

    bg = template.background_path if template.background_path else None
    cmd = build_ffmpeg_cmd(bg, mp3_path, waveform_path, output_path, template, title, duration_secs)

    cmd_str = " ".join(cmd)
    logger.info("FFmpeg command: %s", cmd_str)

    try:
        proc = await asyncio.create_subprocess_exec(
            *cmd,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
        _, stderr = await proc.communicate()
        stderr_log = stderr.decode("utf-8", errors="replace")

        if proc.returncode != 0:
            logger.error("FFmpeg failed (exit %d):\n%s", proc.returncode, stderr_log[-3000:])
            raise RuntimeError(
                f"FFmpeg exited with code {proc.returncode}. "
                f"Last output:\n{stderr_log[-1000:]}"
            )

        logger.info("FFmpeg completed successfully → %s", output_path)
        return cmd, stderr_log

    finally:
        # Clean up the waveform temp file regardless of success or failure
        try:
            os.unlink(waveform_path)
        except OSError:
            pass
